// Banco de 100 variantes de imagen (copy corto para el titular de cada post),
// una expansión del sistema de 6 plantillas ya aprobado. El texto largo del
// caption sigue viviendo en contenido/pilares.py — esto es solo el "gancho"
// visual que va en la imagen.

export const MITOS = [
  ["Vender al Estado es solo para empresas grandes", "Las PYMES ganan el 43% de los contratos públicos en Chile."],
  ["Hay que tener “pituto” para ganar una licitación", "Las bases son públicas y la evaluación es reglada — se puede auditar."],
  ["El precio más bajo siempre gana", "El puntaje técnico pesa tanto o más que el precio en la mayoría de las bases."],
  ["Una vez que ganas, te pagan rápido", "Los plazos de pago pueden extenderse — hay que planificar el flujo de caja."],
  ["Las boletas de garantía son solo un trámite", "Un error ahí puede dejarte fuera antes de que evalúen tu oferta."],
  ["Si cumples los requisitos técnicos, ya ganaste", "Cumplir es el mínimo — ahí recién empieza la competencia real."],
  ["Todas las licitaciones son iguales", "Cada ficha de bases tiene sus propias reglas — leerlas mal cuesta caro."],
  ["No hace falta leer las bases completas", "Las descalificaciones casi siempre están en la letra chica."],
  ["El Estado nunca reclama, solo paga", "Hay multas, resciliaciones y evaluación de proveedores — se lleva historial."],
  ["Ser “boletero” es 100% seguro", "Una mala entrega también deja huella en tu ficha de proveedor."],
  ["Mercado Público es solo para servicios", "También hay licitaciones de bienes, obras, y compras ágiles de todo tipo."],
  ["Las compras ágiles no sirven para escalar", "Son la puerta de entrada — de ahí se pasa a licitaciones más grandes."],
  ["Sin experiencia previa no te evalúan", "Muchas bases valoran la propuesta técnica, no solo el historial."],
  ["Los plazos de pago son iguales que en el privado", "El Estado tiene sus propios tiempos — hay que conocerlos antes de ofertar."],
  ["No necesitas flujo de caja para vender al Estado", "Financiar la producción mientras esperas el pago es parte del juego."],
  ["Ganar la licitación es el final del proceso", "Ahí empieza lo importante: cumplir el contrato sin perder plata."],
  ["Cualquier error de forma se corrige después", "La mayoría de las bases no dan segundas oportunidades."],
];

export const TIPS = [
  ["Lee las bases HASTA EL FINAL", "Las causales de descalificación casi siempre están en el último tercio."],
  ["Verifica tu inscripción en Chileproveedores", "Una inscripción vencida te deja fuera antes de competir."],
  ["Calcula tu margen real, no el que “suena bien”", "Incluye flete, garantías y el costo de esperar el pago."],
  ["Responde EXACTAMENTE lo que piden las bases", "No lo que tú crees que es mejor — lo que se pide, se evalúa."],
  ["Guarda comprobante de cada entrega", "En una licitación pública, lo que no se documenta no existe."],
  ["Revisa el cronograma antes de ofertar", "Un plazo de entrega imposible te descalifica igual que un precio alto."],
  ["No subestimes la boleta de garantía", "El monto y la vigencia mal calculados anulan tu oferta."],
  ["Aclara dudas en el foro de preguntas", "Es tu única vía formal — un supuesto mal hecho sale caro después."],
  ["Compara bases similares antes de ofertar", "Te ayuda a detectar qué pide realmente cada institución."],
  ["Ten tu documentación legal siempre al día", "Certificados vencidos son la descalificación más evitable de todas."],
  ["No ofertes por ofertar", "Cada propuesta mal calculada te resta tiempo para las que sí puedes ganar."],
  ["Define tu capacidad real de producción", "Ganar y no poder cumplir sale más caro que no ganar."],
  ["Usa las compras ágiles para partir", "Menos competencia, ciclo más corto, aprendes las reglas del juego rápido."],
  ["Revisa el histórico de adjudicaciones", "Te dice quién compite realmente en tu rubro y a qué precio."],
  ["Prepara tu oferta con anticipación", "Las bases mal leídas a última hora son la fuente #1 de errores."],
  ["Diversifica las instituciones a las que postulas", "No dependas de un solo comprador del Estado."],
  ["Ten un flujo de caja separado para el Estado", "Los tiempos de pago no son los del retail."],
];

export const HISTORIAS = [
  ["Perdí mi primera licitación por un detalle administrativo", "Ahí entendí cómo funciona realmente el Estado como cliente."],
  ["Una boleta de garantía mal calculada", "Me dejó fuera de una licitación de $80 millones."],
  ["Gané una licitación y casi quiebro", "Por no calcular bien el flujo de caja antes de ofertar."],
  ["Un proveedor pequeño le ganó a una empresa grande", "Solo por leer mejor las bases."],
  ["La primera vez que postulé, ofertaba el precio más bajo", "Y perdía siempre."],
  ["Aprendí a leer una ficha de bases completa", "Después de perder por una cláusula que ignoré."],
  ["Un cliente del Estado se demoró 90 días en pagar", "Esa espera casi me deja sin caja."],
  ["Una PYME ganó su primera compra ágil sin currículum", "Solo con una propuesta bien armada."],
  ["Un error de tipeo en el nombre de la empresa", "Anuló una oferta completa."],
  ["Descalifiqué mi propia oferta por no subir un anexo", "Estaba completo, pero en la carpeta equivocada."],
  ["La competencia bajó tanto el precio", "Que ni ellos pudieron cumplir el contrato después."],
  ["Postulé sin estar inscrito en Chileproveedores", "Ni siquiera llegué a competir."],
  ["Un proveedor pyme ganó 5 compras ágiles seguidas", "Por especializarse en un solo rubro."],
  ["Perdimos una licitación por 2 días", "De plazo de entrega mal calculados."],
  ["La primera vez que gané, no sabía algo clave", "También tenía que rendir cuenta técnica."],
  ["Un cliente institucional se volvió el más estable", "Que tuvo la empresa durante 3 años."],
  ["Cambié de vender “lo que tenía” a vender “lo que pedían”", "Ahí empezó a funcionar de verdad."],
];

export const BACKSTAGE = [
  ["Escribí este libro porque vi el mismo error", "Repetirse cientos de veces en PYMES distintas."],
  ["No es teoría", "Es lo que aprendí a golpes ayudando a postular a licitaciones públicas en Chile."],
  ["El libro que me hubiera gustado tener", "Antes de mi primera licitación."],
  ["Cada capítulo nace de una pregunta real", "Que me hicieron proveedores del Estado."],
  ["El libro no promete atajos", "Promete entender las reglas del juego."],
  ["Escribirlo me obligó a ordenar años de experiencia", "En algo que se pudiera enseñar."],
  ["Quería un libro corto y directo", "Sin relleno — como me hubiera gustado leerlo yo."],
  ["¿Por dónde empiezo?", "La misma pregunta que me hicieron cientos de veces en redes."],
  ["No hay fórmulas mágicas en el libro", "Hay proceso, y el proceso sí se puede aprender."],
  ["Cada mito que desarmo en el libro", "Me lo creí yo también, en algún momento."],
  ["El objetivo no es que ganes tu primera licitación", "Es que no quiebres ganándola."],
  ["Escribí este libro pensando en una PYME específica", "La que recién se inscribe en Mercado Público."],
  ["Detrás de cada capítulo hay una licitación real", "Que perdí, gané, o aprendí a tiempo."],
  ["El título lo dice todo", "Se puede vender al Estado, pero hay que hacerlo sabiendo cómo."],
  ["Lo que se dice de vender al Estado", "Vs. lo que realmente pasa en la práctica."],
  ["Este libro es una versión ordenada", "De años de respuestas sueltas en comentarios y DMs."],
  ["Lo escribí para PYMES, no para consultoras", "Con el lenguaje con el que yo mismo aprendí."],
];

export const PRUEBA_SOCIAL = [
  "Ojalá lo hubiera leído antes de mi primera postulación.",
  "Por fin alguien explica esto en simple.",
  "Lo recomendé a todo mi equipo de ventas.",
  "Cambié la forma en que leo las bases después de este libro.",
  "Es el libro que le hubiera regalado a mi yo de hace 5 años.",
  "Entendí en un capítulo lo que llevaba meses tratando de entender solo.",
  "Directo, sin vueltas, con ejemplos reales — se nota que lo vivió.",
  "Lo leí en un fin de semana y ya lo estoy aplicando en mi próxima oferta.",
  "Explica los errores que yo mismo estaba cometiendo sin darme cuenta.",
  "Un antes y un después en cómo preparo mis licitaciones.",
  "Se lo pasé a toda la PYME — ahora todos hablamos el mismo idioma.",
  "Nadie me había explicado el flujo de caja del Estado así de claro.",
  "Menos teoría, más “esto es lo que realmente pasa” — se agradece.",
  "Volví a leer el capítulo de boletas de garantía tres veces, valía la pena.",
  "Es el manual que faltaba para las PYMES que recién parten con el Estado.",
  "Aprendí más en este libro que en un año postulando a ciegas.",
];

export const CTA = [
  ["Ya está disponible en Amazon", "Si vendes o quieres vender al Estado en Chile, este libro te ahorra meses de prueba y error."],
  ["¿Inscrito en Mercado Público pero sin ganar aún?", "Empieza por acá."],
  ["De PYME a PYME", "Todo el proceso de vender al Estado, explicado sin vueltas."],
  ["Disponible en papel y digital", "Link en bio."],
  ["¿Las licitaciones te suenan a chino?", "Este libro es tu punto de partida."],
  ["Años de errores (y aciertos)", "Vendiendo al Estado chileno, resumidos en un libro."],
  ["Para proveedores cansados de postular a ciegas", "Ya está disponible."],
  ["Ya puedes conseguirlo en Amazon", "Envío disponible a todo Chile."],
  ["Si esto te ha servido...", "El libro va mucho más a fondo. Link en bio."],
  ["El mindset público-digital que necesitas", "Para vender al Estado, en un libro."],
  ["No es solo teoría de licitaciones", "Es la guía que faltaba para PYMES chilenas."],
  ["Prepara tu próxima licitación", "Con las reglas claras — consíguelo hoy."],
  ["El libro que le regalarías a cualquier PYME", "Que recién parte con el Estado."],
  ["Sin relleno, directo al proceso real", "Disponible ahora en Amazon."],
  ["Deja de perder licitaciones por errores evitables", "El libro te muestra cuáles son."],
  ["Todo lo que aprendí vendiendo al Estado", "En un solo lugar. Ya disponible."],
];
