project_id = "euzqadopjvdszcdjegmo"

[functions.scoring-ai]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.matching-ai]
verify_jwt = false

[functions.odoo-proxy]
verify_jwt = false

[functions.send-licitacion-to-odoo]
verify_jwt = false

[functions.extension-api]
verify_jwt = false

[functions.resumir-bases]
verify_jwt = false

[functions.mercadopublico-api]
verify_jwt = false

[functions.sync-health]
verify_jwt = false
