-- Tickets de soporte: registro de las conversaciones/casos que Evaristo canaliza
-- al equipo. Los inserts los hace la edge function `soporte-ticket` con service
-- role (bypassa RLS); los admins pueden leer y gestionar desde la app.
create table if not exists public.soporte_tickets (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  cliente_id uuid references public.clientes(id) on delete set null,
  user_id uuid,
  email text not null,
  nombre text,
  empresa text,
  telefono text,
  canal text not null default 'app',
  pantalla text,
  asunto text,
  mensaje text,
  conversacion jsonb not null default '[]'::jsonb,
  estado text not null default 'abierto' check (estado in ('abierto','en_proceso','resuelto')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_soporte_tickets_estado on public.soporte_tickets(estado, created_at desc);
create index if not exists idx_soporte_tickets_cliente on public.soporte_tickets(cliente_id);
create index if not exists idx_soporte_tickets_email on public.soporte_tickets(lower(email));

alter table public.soporte_tickets enable row level security;

-- Solo administradores pueden ver y gestionar los tickets desde la app.
drop policy if exists "admin_lee_tickets" on public.soporte_tickets;
create policy "admin_lee_tickets" on public.soporte_tickets
  for select using (public.is_admin());

drop policy if exists "admin_gestiona_tickets" on public.soporte_tickets;
create policy "admin_gestiona_tickets" on public.soporte_tickets
  for update using (public.is_admin()) with check (public.is_admin());
