-- "Quién vende esto al Estado" buscaba con las dos primeras palabras del nombre de ítem
-- ("Software de"), una categoría genérica de Mercado Público: aparecía Lirmi (software
-- educativo) en una compra de licencias Google/Adobe. Ahora la competencia se arma por niveles
-- con las marcas y productos reales de la DESCRIPCIÓN de cada ítem: frases exactas
-- ("google workspace"); si hay menos de 3 proveedores, marca sola; si sigue vacío, nombre de
-- la licitación. La ficha del libro y el estudio profundo usan experto_competencia_licitacion.
-- (Aplicado en producción como competencia_por_producto_real, competencia_por_marca y
-- competencia_licitacion_por_niveles; ver esas migraciones en supabase_migrations.)
-- Umbral (competencia_licitacion_umbral): nivel marca exige 2 proveedores; el nombre de la
-- licitación solo se usa cuando no trae ítems. Si no hay datos, el libro no muestra el bloque.
